trigger: none

pr: none

variables:
- name: devEnvironment
  value: dev

resources:
  pipelines:
  - pipeline: cipipeline
    # TODO: Update with the name of your CI pipeline
    source: 'mirzaciri.logicapps_devops - ci'
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-18.04
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              # TODO: Fill in with the name of your Azure service connection
              azureSubscription: 'azure_mirza_2s'
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              deploymentMethod: 'zipDeploy'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure_mirza_2s'
              scriptType: 'ps'
              scriptLocation: 'scriptPath'
              scriptPath: './Generate-Connections.ps1'
              arguments: '-resourceGroup rg-wus-testinglogicapp-dev -outputLocation connections.json -withFunctions'
